#!/usr/bin/env python3
"""Generate one MP3 per slide narration using edge-tts (ne-NP-HemkalaNeural),
plus manifest.json / manifest.js mapping each slide to its audio file and
per-sentence start times (media seconds) for read-along highlighting.

Two-step build (run from this directory):
    node extract_narrations.js      # decks -> narrations.json
    pip install --user edge-tts
    python3 generate_audio.py       # narrations.json -> *.mp3 + manifest.*

Sentence splitting mirrors the JS engine: /[^।!?]+[।!?]*/g
Per-sentence start times come from edge-tts SentenceBoundary events (1:1 with
our split); a proportional-by-length fallback covers the rare merge mismatch.
"""
import asyncio
import json
import os
import re
import sys

import edge_tts

HERE = os.path.dirname(os.path.abspath(__file__))
NARR = os.path.join(HERE, "narrations.json")
OUT_DIR = HERE

VOICE = "ne-NP-HemkalaNeural"
RATE = "-8%"      # gentle, soothing baseline; UI speed slider adjusts playbackRate live
PITCH = "-2Hz"

CONCURRENCY = 4
MAX_RETRIES = 4

SENT_RE = re.compile(r"[^।!?]+[।!?]*")
STRIP_RE = re.compile(r"[\s।!?,.‍‌]+")  # whitespace + common punctuation


def split_sentences(text):
    return [s.strip() for s in SENT_RE.findall(text) if s.strip()]


def norm_len(s):
    return len(STRIP_RE.sub("", s))


async def synth_slide(sem, deck_id, idx, text, result):
    async with sem:
        out_mp3 = os.path.join(OUT_DIR, f"{deck_id}-{idx}.mp3")
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                comm = edge_tts.Communicate(text, VOICE, rate=RATE, pitch=PITCH)
                audio = bytearray()
                bounds = []  # (offset_sec, end_sec) per TTS sentence, in order
                async for chunk in comm.stream():
                    if chunk["type"] == "audio":
                        audio.extend(chunk["data"])
                    elif chunk["type"] in ("SentenceBoundary", "WordBoundary"):
                        off = chunk["offset"] / 10_000_000.0
                        dur = chunk.get("duration", 0) / 10_000_000.0
                        bounds.append((off, off + dur))
                if not audio:
                    raise RuntimeError("no audio bytes")
                with open(out_mp3, "wb") as f:
                    f.write(audio)

                sents = split_sentences(text)
                total_dur = bounds[-1][1] if bounds else 0.0

                if len(bounds) == len(sents) and bounds:
                    # Ideal path: TTS split matches ours 1:1 — use offsets directly.
                    starts = [round(b[0], 3) for b in bounds]
                else:
                    # Fallback: distribute by cumulative character length across the
                    # measured total duration.
                    lens = [max(1, norm_len(s)) for s in sents]
                    tot = sum(lens)
                    acc = 0
                    starts = []
                    for L in lens:
                        starts.append(round(total_dur * acc / tot, 3))
                        acc += L

                result[deck_id][idx] = {
                    "file": f"{deck_id}-{idx}.mp3",
                    "dur": round(total_dur, 3),
                    "sentences": starts,
                }
                tag = "1:1" if len(bounds) == len(sents) else f"FALLBACK {len(bounds)}vs{len(sents)}"
                sys.stdout.write(f"  ✓ {deck_id}-{idx}  ({len(sents)} sentences, {tag}, {len(audio)//1024}KB)\n")
                sys.stdout.flush()
                return
            except Exception as e:  # noqa
                if attempt == MAX_RETRIES:
                    sys.stdout.write(f"  ✗ {deck_id}-{idx} FAILED: {e}\n")
                    sys.stdout.flush()
                    result[deck_id][idx] = {"file": None, "sentences": []}
                    return
                await asyncio.sleep(1.5 * attempt)


async def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(NARR) as f:
        narrations = json.load(f)

    result = {deck: [None] * len(slides) for deck, slides in narrations.items()}
    sem = asyncio.Semaphore(CONCURRENCY)
    tasks = []
    for deck_id, slides in narrations.items():
        for idx, text in enumerate(slides):
            tasks.append(synth_slide(sem, deck_id, idx, text, result))
    await asyncio.gather(*tasks)

    manifest = {
        "voice": VOICE,
        "rate": RATE,
        "pitch": PITCH,
        "decks": result,
    }
    with open(os.path.join(OUT_DIR, "manifest.json"), "w") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=1)

    # Also emit a script-loadable form so the page works without fetch()/CORS
    # (mirrors how the deck files are loaded via <script> injection).
    with open(os.path.join(OUT_DIR, "manifest.js"), "w") as f:
        f.write("/* Auto-generated by generate_audio.py. Maps each deck+slide to its\n")
        f.write("   pre-rendered Nepali narration MP3 and per-sentence start times (media\n")
        f.write("   seconds) for read-along highlighting. Do not edit by hand. */\n")
        f.write("window.NEPALI_AUDIO = ")
        json.dump(manifest, f, ensure_ascii=False)
        f.write(";\n")

    total = sum(len(s) for s in result.values())
    failed = sum(1 for s in result.values() for x in s if not x or not x["file"])
    print(f"\nDone: {total} slides, {failed} failed. Manifest -> {OUT_DIR}/manifest.json")


if __name__ == "__main__":
    asyncio.run(main())
