#!/usr/bin/env python3
"""Shared builder for narrated-presentation decks across courses.

A course provides its content as a list of MODULES (plain dicts, authored by
hand — this is the expensive, human part). This helper turns that content into
the exact on-disk contract the shared presentation engine expects:

    <course>/data/english/<id>.js     window.ENGLISH_DECKS[id]
    <course>/data/nepali/<id>.js      window.NEPALI_DECKS[id]
    <course>/data/pres-titles.js      window.PRES_TITLES = { ne:{}, en:{} }

Each module dict:
    {
      "id": "running-local-llms",
      "title": "Ollama & Hugging Face: …",     # matches SCHEDULE title
      "subtitle_en": "A model on your own laptop",   # poetic one-liner
      "subtitle_ne": "आफ्नै ल्यापटपमा एउटा मोडेल",
      "intro_en": "run a real LLM locally with no API key",
      "intro_ne": "कुनै API key बिना local मै LLM चलाउने",
      "slides": [
        { "heading": "…",             # HTML allowed
          "bullets": ["…"],           # optional, HTML allowed
          "code": "…",                # optional, escaped by engine
          "big": "…",                 # optional pull-quote, HTML allowed
          "narration_en": "…",        # authored English narration prose
          "narration_ne": "…" },      # idiomatic Nepali narration
        ...
      ],
    }

Slide bodies (heading/bullets/code/big) are shared verbatim between the two
language decks — only the narration differs, exactly like DSA. Run per course;
it merges pres-titles.js so you can build one lesson at a time.
"""
import json
import os
import re


def _js_deck(var, deck):
    """Serialize one deck to a `window.<VAR>[id] = {...}` assignment. We emit
    real JS (not JSON) so the file loads via <script> injection like DSA's."""
    out = [f"window.{var} = window.{var} || {{}};",
           f"window.{var}[{json.dumps(deck['id'])}] = {json.dumps(deck, ensure_ascii=False, indent=2)};",
           ""]
    return "\n".join(out)


def _slide_body(s):
    b = {"heading": s["heading"], "narration": s["_narr"]}
    if s.get("bullets"):
        b["bullets"] = s["bullets"]
    if s.get("code"):
        b["code"] = s["code"]
    if s.get("big"):
        b["big"] = s["big"]
    return b


def build(course_dir, modules):
    en_dir = os.path.join(course_dir, "data", "english")
    ne_dir = os.path.join(course_dir, "data", "nepali")
    os.makedirs(os.path.join(en_dir, "audio"), exist_ok=True)
    os.makedirs(os.path.join(ne_dir, "audio"), exist_ok=True)

    # merge with any existing pres-titles so we can build incrementally
    titles_path = os.path.join(course_dir, "data", "pres-titles.js")
    titles = {"ne": {}, "en": {}}
    if os.path.exists(titles_path):
        txt = open(titles_path, encoding="utf-8").read()
        m = re.search(r"window\.PRES_TITLES\s*=\s*(\{.*\});", txt, re.S)
        if m:
            try:
                titles = json.loads(m.group(1))
                titles.setdefault("ne", {}); titles.setdefault("en", {})
            except Exception:
                pass

    for mod in modules:
        for lang, var, out_dir, narr_key, sub_key in (
            ("en", "ENGLISH_DECKS", en_dir, "narration_en", "subtitle_en"),
            ("ne", "NEPALI_DECKS", ne_dir, "narration_ne", "subtitle_ne"),
        ):
            slides = []
            for s in mod["slides"]:
                s2 = dict(s)
                s2["_narr"] = s[narr_key]
                slides.append(_slide_body(s2))
            deck = {
                "id": mod["id"],
                "title": mod["title"],
                "titleNe": mod[sub_key],
                "intro": mod["intro_en"] if lang == "en" else mod["intro_ne"],
                "slides": slides,
            }
            with open(os.path.join(out_dir, mod["id"] + ".js"), "w", encoding="utf-8") as f:
                f.write("/* Auto-generated by pres_build.py from authored content. */\n")
                f.write(_js_deck(var, deck))
        titles["en"][mod["id"]] = mod["subtitle_en"]
        titles["ne"][mod["id"]] = mod["subtitle_ne"]

    with open(titles_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by pres_build.py — per-deck poetic subtitles for the\n")
        f.write("   presentation index cards. window.PRES_TITLES = { ne:{}, en:{} }. */\n")
        f.write("window.PRES_TITLES = ")
        json.dump(titles, f, ensure_ascii=False, indent=1)
        f.write(";\n")

    print(f"built {len(modules)} deck(s) into {course_dir}; pres-titles now has "
          f"{len(titles['en'])} entries")
